on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  terraform:
    strategy:
      matrix:
        terraform: ['1.8.0', '1.7.5']

    runs-on: macos-latest-xlarge

    steps:
      - uses: actions/checkout@v2
        with:
          repository: philips-labs/terraform-aws-github-runner

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: ${{ matrix.terraform }}

      - name: Setup Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ matrix.terraform }}/terraform_${{ matrix.terraform}}_darwin_arm64.zip
          unzip terraform_${{ matrix.terraform}}_darwin_arm64.zip
          mv terraform /usr/local/bin/

      - name: Terraform Version
        run: terraform --version
        working-directory: examples/multi-runner

      - name: Terraform Init
        run: terraform init --upgrade
        working-directory: examples/multi-runner

      - name: Terraform Validate
        run: time terraform validate
        working-directory: examples/multi-runner

      - name: Terraform Validate
        run: time terraform validate
        working-directory: examples/multi-runner        